### ISSUE TITLE
Improve audio media type parsing

### ISSUE THREAD

**Issue by MattBlissett** [gbif/parsers#14]
* https://www.gbif.org/dataset/f11db245-3f9f-4fc6-a0cc-12b4124d081b says `audio/mpeg3`, which we should convert to `audio/mpeg`.
* https://www.gbif.org/dataset/cb6e66f1-3056-404d-a341-bb856762c57c says `audio/mpeg` and has identifiers ending `m4a`, and is really `audio/mp4`
* https://www.gbif.org/dataset/b1047888-ae52-4179-9dd5-5448ea342a24 and https://www.gbif.org/dataset/b7ec1bf8-819b-11e2-bad2-00145eb45e9a say `audio/mp3`, which should be `audio/mpeg`

This will help https://github.com/gbif/portal-feedback/issues/1630

**Comment by MattBlissett** [comment]
References: 
https://wiki.whatwg.org/wiki/Video_type_parameters
https://www.iana.org/assignments/media-types/media-types.xhtml#audio

**Comment by MortenHofft** [comment]
```
row format count works example
1 audio/x-flac	2		NOT 1882615644
2	audio/ogg	14		OK 1271693629
3	audio/x-wav	68 		OK 1271693192
4	audio/mpeg	30883 	OK 1571572483
5	audio/wav	18 		OK 1317313403
6	audio/mp3	16416 	OK 1421199821
7	audio/mp4	42 		OK 1882578898
8	audio/x-aiff	22	NOT 1271780103
9	audio/mpeg3	55418 	NOT 1058481761 (but works if treated like mp3)
```

notice line 9: 55K audio files with format `audio/mpeg3`. the html5 audio tag won't play that. But for the examples i tried (e.g. 1058481761) the file ending is mp3 and works if format set as such.
