### ISSUE TITLE
Support  KM-to-Metre conversion

### ISSUE THREAD

**Issue by qifeng-bai** [gbif/parsers#21]
At this moment,  MeterRangeParser is able to convert  inch/feet to meters. 
We also need to 
1, support conversion of KM to meters. 
2, support patterns of  km, kilometers, kilometres, feet, f, inch, inches

**Comment by MattBlissett** [comment]
Is it necessary to support `f` alone, or was that just an idea? I see extremely few cases of this unit in GBIF's data, and it's ambiguous with fathoms (which I've added).

I'll merge the PR without `f` for the moment.

**Comment by mdoering** [comment]
Isn't `ft` used as a short version for feet?

**Comment by qifeng-bai** [comment]
> Isn't `ft` used as a short version for feet?

ft is already supported.  @MattBlissett I am OK without 'f'. I followed what Biocache does.

**Comment by MattBlissett** [comment]
OK, then this is completed. (Markus, `ft` is included in the change.)

 You can use version `0.52-SNAPSHOT` in pipelines, and we'll release it when it's necessary to release pipelines.  (I think there will be some other minor changes to parsers this week.)
