### ISSUE TITLE
False "Recorded date mismatch" issue reported by the date parser

### ISSUE THREAD

**Issue by cgendreau** [gbif/parsers#6]
In the occurrence interpreter, when an `eventDate` that can not be parsed with full confidence is compared with the atomized version of that date, the date parser reports a "Recorded date mismatch" even if the atomized date would match one of the possible dates from the `eventDate`.

Example:
- eventDate: 5/2/2014
- year: 2014
- month: 2
- day: 5

In order to solve this issue we must change the interface of `ParseResult` to allow `alternativePayload` to be returned.

**Comment by ahahn-gbif** [comment]
example: https://www.gbif.org/occurrence/1585284262
all records from this filter: https://www.gbif.org/occurrence/search?dataset_key=2dca5fbd-1989-4634-b745-269ff1098ebf&issue=RECORDED_DATE_MISMATCH
