### ISSUE TITLE
Wrong usage of 'Identified date unlikely'

### ISSUE THREAD

**Issue by cgendreau** [gbif/parsers#9]
The parser will flag `dateIdentified` as "Identified date unlikely" if the date is provided as partial date.

We do not handle partial dates at the moment but `IDENTIFIED_DATE_UNLIKELY` is not the right flag, `IDENTIFIED_DATE_INVALID` would be more appropriate until we add the support for partial date.

**Comment by MattBlissett** [comment]
Duplicates https://github.com/gbif/portal-feedback/issues/1488 (Donald wins), and fixed in UAT anyway.
